import type { TenantBrandTokens } from "@life-community-os/design-tokens";

/** Coastal community brand — must not reuse Panorámica greens or Valley slate. */
export const oceanHillsTheme: TenantBrandTokens = {
  name: "Ocean Hills Community",
  shortName: "Ocean Hills",
  logoText: "Ocean Hills",
  tagline: "Live by the water",
  identity: {
    territoryName: "Ocean Hills",
    defaultAreaName: "Marina District",
    municipalityName: "Ocean Hills",
    homeCallout: "Today in Ocean Hills",
    pulseTitleTemplate: "Today in {territory}",
    wordmarkPrimary: "OCEAN",
    wordmarkSecondary: "HILLS",
    weatherLabel: "21° · Sea breeze",
    weatherTemperature: "21°",
    weatherCondition: "Sea breeze",
  },
  colors: {
    brandPrimary: "#0B7285",
    brandPrimaryHover: "#086575",
    brandPrimarySubtle: "#E3F6F8",
    brandSecondary: "#5C6B73",
    brandAccent: "#F08C00",
    brandAccentSubtle: "#FFF4E0",
    brandSea: "#1983A0",
    brandSeaSubtle: "#D5F0F6",
    bgApp: "#F3F8F9",
    bgElevated: "#FFFFFF",
    bgMuted: "#E4EEF0",
    bgHeroScrim: "rgba(8, 32, 40, 0.48)",
    textPrimary: "#0B1F26",
    textSecondary: "#2F4A52",
    textTertiary: "#6B8188",
    textInverse: "#FFFFFF",
    borderSubtle: "#D5E4E8",
    borderStrong: "#B7CDD3",
    success: "#2B8A3E",
    successSubtle: "#D3F9D8",
    warning: "#E67700",
    warningSubtle: "#FFF3BF",
    danger: "#C92A2A",
    dangerSubtle: "#FFE3E3",
    info: "#0B7285",
    infoSubtle: "#E3F6F8",
  },
  defaultMode: "day",
  modes: {
    night: {
      brandPrimary: "#66D9E8",
      brandPrimaryHover: "#3BC9DB",
      brandPrimarySubtle: "rgba(102, 217, 232, 0.16)",
      brandSecondary: "#94A3B8",
      brandAccent: "#FFD43B",
      brandAccentSubtle: "rgba(255, 212, 59, 0.16)",
      brandSea: "#22D3EE",
      brandSeaSubtle: "rgba(34, 211, 238, 0.16)",
      bgApp: "#04141A",
      bgElevated: "#0B2430",
      bgMuted: "#0F2C38",
      bgHeroScrim: "rgba(0, 0, 0, 0.55)",
      textPrimary: "#F1FAFC",
      textSecondary: "#C5DCE2",
      textTertiary: "#8AA8B0",
      textInverse: "#FFFFFF",
      textOnAction: "#04141A",
      borderSubtle: "rgba(255, 255, 255, 0.10)",
      borderStrong: "rgba(255, 255, 255, 0.16)",
      success: "#69DB7C",
      successSubtle: "rgba(105, 219, 124, 0.16)",
      warning: "#FFD43B",
      warningSubtle: "rgba(255, 212, 59, 0.16)",
      danger: "#FF8787",
      dangerSubtle: "rgba(255, 135, 135, 0.16)",
      info: "#66D9E8",
      infoSubtle: "rgba(102, 217, 232, 0.16)",
    },
  },
  imagery: {
    splash: "",
    homeHero: "",
  },
};
