export type {
  TenantResolutionSource,
  TenantContext,
  PlatformContext,
  ExecutionContext,
  TenantContextCarrier,
} from "./tenant-context";

export type {
  ActingIdentityId,
  AuthenticationResult,
  AuthorizationDecision,
} from "./security-boundaries";

export type {
  PlatformModule,
  PlatformModuleCategory,
  PlatformModuleStatus,
  PlatformModuleNavigation,
  PlatformModuleRegistryIssue,
  PlatformModuleRegistryDocument,
} from "./module-registry";
export {
  PLATFORM_MODULE_REGISTRY_VERSION,
  PLATFORM_MODULE_REGISTRY,
  listPlatformModules,
  listRootPlatformModules,
  getPlatformModuleById,
  listPlatformModulesByFeatureFlag,
  validatePlatformModuleRegistry,
  getPlatformModuleRegistryDocument,
} from "./module-registry";

export type {
  TenantConfiguration,
  TenantConfigurationBranding,
  TenantConfigurationTerritory,
  TenantModuleEnablement,
  TenantPackConfigurationSource,
  TenantConfigurationSource,
  TenantConfigurationPreset,
} from "./tenant-configuration";
export {
  resolveModuleEnabledFromFeatures,
  tenantPackToTenantConfiguration,
  resolveTenantConfiguration,
  isTenantModuleEnabled,
  applyTenantConfigurationPreset,
  assertTenantConfigurationCoversRegistry,
} from "./tenant-configuration";

export {
  mergeHousingTenantModuleConfig,
  housingTenantModuleConfigToRecord,
  resolveHousingTenantModuleConfig,
  isHousingEnabledInTenantConfiguration,
  withHousingTenantModuleConfig,
} from "./housing-config";

/** Contextual Conversation Layer (ADR-043) — contracts + adapters. */
export type {
  ConversationContext,
  ConversationContextType,
  KnownConversationContextType,
  ConversationContextIssue,
  ConversationContextIssueCode,
  Conversation,
  ConversationStatus,
  ConversationParticipantPolicy,
  ConversationIssue,
  ConversationIssueCode,
  Message,
  MessageMediaRef,
  MessageIssue,
  MessageIssueCode,
  ReactionType,
  MessageReactionSummary,
  MessageReactor,
  MessageActionKind,
  MessageActionAvailability,
  AttachmentPickerKind,
  VoiceRecorderState,
  QuickActionKind,
  RetentionPolicy,
  RetentionPolicyType,
  RetentionPolicyIssue,
  RetentionPolicyIssueCode,
  ContextLifecycleState,
  ConversationParticipantRole,
  ConversationParticipant,
  ConversationContextAdapterEnv,
  ConversationContextAdapter,
  ConversationContextAdapterRegistry,
  ExperienceConversationSnapshot,
  GroupConversationSnapshot,
  WorkConversationSnapshot,
  MarketplaceConversationSnapshot,
  PlaceConversationSnapshot,
  HousingConversationSnapshot,
  ServiceRequestConversationSnapshot,
  CommunityDiscussionSnapshot,
  ReservationConversationSnapshot,
  OfficialConversationSnapshot,
  OfficialEntityKind,
  OfficialInteractionMode,
  ConversationPersistenceMode,
  ConversationRepository,
  ConversationPersistencePlan,
  CommunicationEventType,
  CommunicationEvent,
  CommunicationEventPublisher,
  DeliveryChannelKind,
  DeliveryChannelAdapter,
} from "./communication";
export {
  KNOWN_CONVERSATION_CONTEXT_TYPES,
  isKnownConversationContextType,
  validateConversationContext,
  validateConversation,
  validateMessage,
  REACTION_TYPES,
  REACTION_TYPE_GLYPH,
  isReactionType,
  emptyMessageReactionSummary,
  MESSAGE_ACTION_KINDS,
  isMessageActionKind,
  DEFAULT_MESSAGE_ACTION_AVAILABILITY,
  ATTACHMENT_PICKER_KINDS,
  isAttachmentPickerKind,
  ATTACHMENT_FOUNDATION_NOTE,
  VOICE_RECORDER_STATES,
  isVoiceRecorderState,
  VOICE_MESSAGE_FOUNDATION_NOTE,
  QUICK_ACTION_KINDS,
  isQuickActionKind,
  RETENTION_POLICY_TYPES,
  DEFAULT_RETENTION_POLICY_IDS,
  validateRetentionPolicy,
  isAdapterModuleAvailable,
  shouldProjectConversationContext,
  createConversationContextAdapterRegistry,
  createExperienceConversationAdapter,
  experienceContextMatches,
  createGroupConversationAdapter,
  createWorkConversationAdapter,
  createMarketplaceConversationAdapter,
  createPlaceConversationAdapter,
  localEntityToPlaceConversationSnapshot,
  createHousingConversationAdapter,
  createServiceRequestConversationAdapter,
  createCommunityDiscussionConversationAdapter,
  COMMUNITY_DISCUSSION_CREATE_CAPABILITY,
  createReservationConversationAdapter,
  createOfficialConversationAdapter,
  allowsOfficialResidentReplies,
  allowsOfficialReactions,
  createDefaultConversationContextAdapterRegistry,
  DEFAULT_CONVERSATION_PERSISTENCE_PLAN,
  COMMUNICATION_EVENT_TYPES,
  createNoopCommunicationEventPublisher,
  isCommunicationEventType,
  DELIVERY_CHANNEL_KINDS,
  isDeliveryChannelKind,
  COMMUNICATION_DELIVERY_ARCHITECTURE_NOTE,
  EPHEMERAL_MEDIA_TTL_PRESETS,
} from "./communication";

/** Participation foundations — Reaction ≠ Support ≠ Vote (Phase 2.5). */
export type {
  SoftReactionKind,
  SoftReactionSummary,
  SupportVisibility,
  SupportRecord,
  SupportAggregate,
  SupportIssue,
  SupportIssueCode,
  VoteStatus,
  VoteOption,
  VoteEligibility,
  VoteDefinition,
  VoteResultTally,
  VoteResults,
  VoteIssue,
  VoteIssueCode,
} from "./participation";
export {
  SOFT_REACTION_KINDS,
  isSoftReactionKind,
  emptySoftReactionSummary,
  PARTICIPATION_SEPARATION_NOTE,
  SUPPORT_VISIBILITY_MODES,
  isSupportVisibility,
  validateSupportRecord,
  VOTE_STATUSES,
  isVoteStatus,
  validateVoteDefinition,
  VOTE_FOUNDATION_NOTE,
} from "./participation";

/** Platform Core Notifications spine (ADR-019 / Phase 2.2). */
export type {
  NotificationStatus,
  NotificationCategory,
  NotificationContextRef,
  Notification,
  NotificationEventType,
  NotificationRecipientSelector,
  NotificationEvent,
  NotificationRecipientResolver,
  NotificationFactory,
  NotificationInboxPort,
  NotificationDeliveryPort,
} from "./notifications";
export {
  NOTIFICATION_STATUSES,
  NOTIFICATION_CATEGORIES,
  isNotificationStatus,
  isNotificationCategory,
  markNotificationRead,
  markNotificationArchived,
  isNotificationUnread,
  NOTIFICATION_EVENT_TYPES,
  NOTIFICATION_EVENT_CATEGORY,
  isNotificationEventType,
  categoryForNotificationEvent,
  createEmptyNotificationInboxPort,
  createNoopNotificationRecipientResolver,
  createNoopNotificationDeliveryPort,
} from "./notifications";

/** Platform Core Files & Media (ADR-020 / D.0.5c) — contracts only. */
export type {
  FileType,
  FileReferenceStatus,
  FileOwnerContext,
  FileReference,
  FileReferenceIssue,
  FileReferenceIssueCode,
  FileVariantKind,
  PreferredImageFormat,
  FileMediaFormat,
  FileVariant,
  FileVariantIssue,
  FileVariantIssueCode,
  MediaPipelineStage,
  ImageOptimizationOutputKind,
  ImageOptimizationContract,
  MediaPipelineContract,
  FileAccessEnv,
} from "./files";
export {
  FILE_TYPES,
  FILE_REFERENCE_STATUSES,
  isFileType,
  isFileReferenceStatus,
  isFileReferenceReady,
  validateFileReference,
  FILE_VARIANT_KINDS,
  PREFERRED_IMAGE_FORMATS,
  isFileVariantKind,
  validateFileVariant,
  pickDeliveryVariant,
  DEFAULT_IMAGE_OPTIMIZATION_CONTRACT,
  DEFAULT_MEDIA_PIPELINE_CONTRACT,
  shouldProjectFileReference,
  canDeliverFileReference,
  isFileEligibleForRetentionCleanup,
} from "./files";
