export type {
  TenantResolutionSource,
  TenantContext,
  PlatformContext,
  ExecutionContext,
  TenantContextCarrier,
} from "./tenant-context";

export type {
  ActingIdentityId,
  AuthenticationResult,
  AuthorizationDecision,
} from "./security-boundaries";

export type {
  PlatformModule,
  PlatformModuleCategory,
  PlatformModuleStatus,
  PlatformModuleNavigation,
  PlatformModuleRegistryIssue,
  PlatformModuleRegistryDocument,
} from "./module-registry";
export {
  PLATFORM_MODULE_REGISTRY_VERSION,
  PLATFORM_MODULE_REGISTRY,
  listPlatformModules,
  listRootPlatformModules,
  getPlatformModuleById,
  listPlatformModulesByFeatureFlag,
  validatePlatformModuleRegistry,
  getPlatformModuleRegistryDocument,
} from "./module-registry";

export type {
  TenantConfiguration,
  TenantConfigurationBranding,
  TenantConfigurationTerritory,
  TenantModuleEnablement,
  TenantPackConfigurationSource,
  TenantConfigurationSource,
  TenantConfigurationPreset,
} from "./tenant-configuration";
export {
  resolveModuleEnabledFromFeatures,
  tenantPackToTenantConfiguration,
  resolveTenantConfiguration,
  isTenantModuleEnabled,
  applyTenantConfigurationPreset,
  assertTenantConfigurationCoversRegistry,
} from "./tenant-configuration";

/** Contextual Conversation Layer (ADR-043) — contracts + adapters. */
export type {
  ConversationContext,
  ConversationContextType,
  KnownConversationContextType,
  ConversationContextIssue,
  ConversationContextIssueCode,
  Conversation,
  ConversationStatus,
  ConversationParticipantPolicy,
  ConversationIssue,
  ConversationIssueCode,
  Message,
  MessageMediaRef,
  MessageIssue,
  MessageIssueCode,
  ReactionType,
  MessageReactionSummary,
  QuickActionKind,
  RetentionPolicy,
  RetentionPolicyType,
  RetentionPolicyIssue,
  RetentionPolicyIssueCode,
  ContextLifecycleState,
  ConversationParticipantRole,
  ConversationParticipant,
  ConversationContextAdapterEnv,
  ConversationContextAdapter,
  ConversationContextAdapterRegistry,
  ExperienceConversationSnapshot,
  GroupConversationSnapshot,
  WorkConversationSnapshot,
  CommunityDiscussionSnapshot,
  ReservationConversationSnapshot,
  OfficialConversationSnapshot,
  OfficialEntityKind,
} from "./communication";
export {
  KNOWN_CONVERSATION_CONTEXT_TYPES,
  isKnownConversationContextType,
  validateConversationContext,
  validateConversation,
  validateMessage,
  REACTION_TYPES,
  REACTION_TYPE_GLYPH,
  isReactionType,
  emptyMessageReactionSummary,
  QUICK_ACTION_KINDS,
  isQuickActionKind,
  RETENTION_POLICY_TYPES,
  DEFAULT_RETENTION_POLICY_IDS,
  validateRetentionPolicy,
  isAdapterModuleAvailable,
  shouldProjectConversationContext,
  createConversationContextAdapterRegistry,
  createExperienceConversationAdapter,
  experienceContextMatches,
  createGroupConversationAdapter,
  createWorkConversationAdapter,
  createCommunityDiscussionConversationAdapter,
  COMMUNITY_DISCUSSION_CREATE_CAPABILITY,
  createReservationConversationAdapter,
  createOfficialConversationAdapter,
  createDefaultConversationContextAdapterRegistry,
} from "./communication";
